apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-home-work-1
  namespace: otus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-home-work-1-app
  template:
    metadata:
      labels:
        app: otus-home-work-1-app
    spec:
      restartPolicy: Always
      containers:
        - name: otus-home-work-1-app
          image: ilmirsadykov/otus-home-work-1
          ports:
            - containerPort: 8000
